@startuml
title List-Flag

(*) -d-> [Neuen Planeintrag\nhinzufügen] New
New --> [Autmatisch bei\nRead-to-Write-Zugriff\n(durch Fachanwendung)] Unchanged
Changed --> [Autmatisch bei\nRead-to-Write-Zugriff\n(durch Fachanwendung)] Unchanged
Unchanged --> [Planeintrag\nändern] Changed
Unchanged -d-> [Planeintrag\nentfernen] Removed
Removed  -d-> (*)
@enduml