@startuml
title MedicationRequest Status

(*) -d-> [neuer Planeintrag] active
(*) -d-> [neuer Planeintrag\npausiert] "on-hold"
"on-hold" -r-> [aktivieren] active 
"on-hold" -d-> [stornieren] "entered-in-error"
"on-hold" -l-> [absetzen] stopped
"on-hold" -d-> [beenden] completed
active -l-> [absetzen] stopped
active -r-> [beenden] completed  
active -l-> [pausieren] "on-hold"
active -d-> [stornieren] "entered-in-error"
stopped -d-> (*)
"entered-in-error" -d-> (*)
completed -d-> (*)
@enduml