@startuml
title List Flag

(*) -d-> [neuer Planeintrag] active
(*) -d-> [neuer Planeintrag pausiert] onHold
onHold -r-> [aktivieren] active 
onHold -d-> [stornieren] enteredInError
onHold -l-> [absetzen] stopped
onHold -d-> [beenden] completed
active -l-> [absetzen] stopped
active -r-> [beenden] completed  
active -l-> [pausieren] onHold
active -d-> [stornieren] enteredInError
stopped -d-> (*)
enteredInError -d-> (*)
completed -d-> (*)
@enduml