@startuml
title List-Flag

(*) -d-> [Neuen Planeintrag\nhinzufügen] new
new --> [Automatisch bei\nRead-to-Write-Zugriff\n(durch Fachanwendung)] unchanged
changed --> [Automatisch bei\nRead-to-Write-Zugriff\n(durch Fachanwendung)] unchanged
unchanged --> [Planeintrag\nändern] changed
unchanged -d-> [Planeintrag\nentfernen] removed
removed  -d-> (*)
@enduml