@startuml
skinparam borderColor #000000
skinparam backgroundColor #f5f5f5
skinparam shadowing false
skinparam roundCorner 10
skinparam defaultFontName "Arial"
skinparam defaultFontSize 14
skinparam defaultFontColor #000000

skinparam note {
  BackgroundColor #e0e5f0-#d1d9e6
  BorderColor #8b95a5
  BorderThickness 1
  RoundCorner 8
  Padding 6
  FontColor #111827
  Shadowing true
}

skinparam HyperlinkColor #0000EE
skinparam HyperlinkUnderline false

skinparam sequence {
  ParticipantBorderColor #555555
  ParticipantBackgroundColor #ffffff
  ParticipantFontColor #000000
  ParticipantFontSize 14
  ParticipantPadding 20
  ArrowColor #111827
  ArrowThickness 1
  ArrowFontColor #000000
  ArrowFontSize 13
  GroupBorderColor #111827
  GroupBackgroundColor #eef2ff
  GroupBorderThickness 2
}

skinparam BoxPadding 20
skinparam BoxBorderColor #555555

box "\n  GDA 1  " #9fbac4
  actor GDA_1 as "GDA 1"
end box

box "\n       e-Med Fachanwendung       " #C48778
  participant eMed_FA as "e-Med FA"
end box

box "\n    GDA 2  " #beaebe
  actor GDA_2 as "GDA 2"
end box

box "\n Patient  " #bac38b
  actor Patient as "Patient"
end box


autonumber

 
== Read-to-Write ==

GDA_1 ->> eMed_FA: POST $readtowrite
note over GDA_1
Medikationsplan abrufen, 
mit der Intention zu schreiben
end note

activate eMed_FA
eMed_FA -> eMed_FA: Prüfung auf bestehenden\nMedikationsplan
eMed_FA -> eMed_FA: Erstellt Collection Bundle zur Auslieferung\n(inkl. neuem List.identifier)\nfür Read-to-Write:\n- new|changed → unchanged\n- removed → entfernen

eMed_FA -->> GDA_1: Collection Bundle + List.identifier
deactivate eMed_FA

activate GDA_1
GDA_1 -> GDA_1: Medikationsplaneinträge\nhinzufügen/ändern/beenden/löschen

note over GDA_1
Medikatiosplan bearbeiten
end note

== Write ==

GDA_1 ->> eMed_FA: POST $write (Transaction Bundle + List.identifier)
deactivate GDA_1


activate eMed_FA
eMed_FA -> eMed_FA: List.identifier im TransactionBundle ==\ntemporär gespeicherter List.identifier?
eMed_FA -> eMed_FA: Validierung des neuen Plans:\nnur erlaubte Änderungen zulassen\n(keine unzulässigen Zustandsübergänge)

alt gültig
  eMed_FA -> eMed_FA: Persistiert neue Version des\nMedikationsplans

  note over eMed_FA
  Neuer Medikationsplan gespeichert
  end note

  eMed_FA -->> GDA_1: OK
else ungültig
  eMed_FA -->> GDA_1: Fehler (Konflikt): ein anderer GDA hat\nzwischenzeitlich geschrieben -> neues Read-to-Write nötig
end
deactivate eMed_FA

center footer Standardablauf Medikationsplan bearbeiten

@enduml