@startuml
skinparam borderColor #000000
skinparam backgroundColor #f5f5f5
skinparam shadowing false
skinparam roundCorner 10
skinparam defaultFontName "Arial"
skinparam defaultFontSize 14
skinparam defaultFontColor #000000

skinparam note {
  BackgroundColor #e0e5f0-#d1d9e6
  BorderColor #8b95a5
  BorderThickness 1
  RoundCorner 8
  Padding 6
  FontColor #111827
  Shadowing true
}

skinparam HyperlinkColor #0000EE
skinparam HyperlinkUnderline false

skinparam sequence {
  ParticipantBorderColor #555555
  ParticipantBackgroundColor #ffffff
  ParticipantFontColor #000000
  ParticipantFontSize 14
  ParticipantPadding 20
  ArrowColor #111827
  ArrowThickness 2
  ArrowFontColor #000000
  ArrowFontSize 13
  GroupBorderColor #111827
  GroupBackgroundColor #f3f4f6
  GroupBorderThickness 1
}

skinparam BoxPadding 20
skinparam BoxBorderColor #555555

box "\n  GDA 1  " #5FA8C6
  actor GDA_1 as "GDA 1"
end box

box "\n       e-Med Fachanwendung       " #C48778
  participant eMed_FA as "e-Med FA"
end box

box "\n    GDA 2  " #8F8CA3
  actor GDA_2 as "GDA 2"
end box

box "\n Patient  " #7FAF87
  actor Patient as "Patient"
end box

autonumber

GDA_1 ->> eMed_FA: $readtowrite\n(Patient)
note over GDA_1, eMed_FA
GDA 1 ruft Medikationsplans ab, mit der Intention zu schreiben
end note

activate eMed_FA
eMed_FA -> eMed_FA: Prüfung auf bestehenden\nMedikationsplan

eMed_FA -> eMed_FA: List-Flags von *new* oder *changed* auf *unchanged* setzen\nList-Entries mit Flag *removed* entfernen\nList-Entries mit abgelaufenem Behandlungszeitraum auf *completed* setzen

eMed_FA -->> GDA_1: Collection Bundle mit List und MedicationRequests zurückliefern

deactivate eMed_FA

note over GDA_1, eMed_FA
Fachanwendung liefert Medikationsplan zurück.
end note

activate GDA_1

GDA_1 -> GDA_1: MedicationRequest erstellen,\nmit Flag "new" der Liste hinzufügen

GDA_1 ->> eMed_FA: $write\n(Patient)

deactivate GDA_1

note over GDA_1, eMed_FA
GDA 1 sendet neuen Medikationsplan zur Fachanwendung
end note

activate eMed_FA

eMed_FA -> eMed_FA: Prüfung, ob Medikationsplan noch aktuell\n(kein anderer GDA hat ein $write durchgeführt)

note over eMed_FA
Fachanwendung speichert Medikationsplan.
end note

deactivate eMed_FA

center footer Sub_UC_06_03 - Medikationsplaneintrag in Medikationsplan hinzufügen

@enduml