@startuml
allowmixing
' !include "https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v3.0.0/icons/font-awesome-5/user_doctor.puml"

' title diagramm
' ICON_DOC(doctor,LIVE,user_doctor,black) #RoyalBlue

' stethoscope	GOV_STETHOSCOPE
' balance_scale	FA5_BALANCE_SCALE
' flask	FA5_FLASK
' hand_holding_medical	FA5_HAND_HOLDING_MEDICAL
' heartbeat	FA5_HEARTBEAT
' comment_medical	FA5_COMMENT_MEDICAL
' clinic_medical	FA5_CLINIC_MEDICAL


skinparam componentStyle uml2
skinparam packageStyle rectangle

skinparam borderColor #555555
skinparam backgroundColor #FFFFFF
skinparam shadowing false
skinparam roundCorner 4
skinparam defaultFontName "Arial"
skinparam defaultFontSize 12
skinparam defaultFontColor #000000

!define COLOR_EMED_FA  #e97232bd

' Styling für UML-Komponenten und Schnittstellen (Klassischer UML-Stil)
skinparam component {
  BackgroundColor COLOR_EMED_FA
  'BorderColor #0366D6
  'FontColor #000000
  'FontStyle bold
}

skinparam interface {
  'BackgroundColor #FFFFFF
  'BorderColor #005CC5
}

left to right direction

title REST-Schnittstellen: https://[server]

interface "/Patient/[id]/MedicationDispense/" as IDurchgAbgabe {
  «POST» $dispense-write [GDA]
  «POST» $dispense-discard [GDA]
  «POST» $reference-plan [GDA]
  «GET» (dispense-read) [GDA, PAT]
  «DELETE» (delete) [PAT]
}

interface "/Patient/[id]/MedicationRequest/" as IMedicationRequest {
  «POST» $prescription-write [GDA]
  «POST» $prescription-discard [GDA]
  «POST» $plan-read [GDA, PAT]
  «POST» $plan-write [GDA]
  «POST» $patient-plan-write [PAT]
  «POST» $plan-delete [PAT]
  «GET» ?category=GeplAbgabe [GDA, PAT]
  «GET» ?category=Planeintrag [GDA, PAT] 
  «DELETE» (delete) [PAT]
} 


interface "/" as IEmed {
  «POST» $groupidentifier-create [GDA]
  «POST» $groupidentifier-prescription-search [GDA]
  «POST» $groupidentifier-dispense-search [GDA]
  «POST» $plan-history-read [GDA, PAT] 
}

' --- SYSTEMKOMPONENTE (ZENTRALER SERVER) ---

component "ELGA\ne-Medikation" as Server {
  port "MedicationDispense\n(Durchgeführte Abgaben)" as p5
  port "MedicationRequest\n(Planeinträge und\nGeplante Abgaben)" as p4
  port "eMed" as p1
}



p5 -up- IDurchgAbgabe
p4 -up- IMedicationRequest
p1 -up- IEmed


legend right
  **Legende Berechtigungen:**
  [GDA] = Gesundheitsdiensteanbieter
  [PAT] = PATIENT: ELGA-Teilnehmer:in
end legend

' --- ARCHITEKTUR-NOTIZEN ---

' note bottom of Server
'   **UML 2.0 Component Specification**
'   Zentrales e-Medikations-System kapselt persistierte
'   Collection Bundles (v.1 / v.2) und Transaction Bundles.
' end note

' note right of IBundle
'   **Ressourcen-Kontext:**
'   Enthält MedicationRequest,
'   Patient, Practitioner.
' end note

@enduml