@startuml
title MedicationRequest.status (geplante Abgabe)

(*) --> ["offen"] active
active --> ["abgelaufen" (automatisch\ndurch Fachanwendung)] stopped
active --> ["eingelöst" (automatisch\ndurch Fachanwendung)] completed
active --> ["storniert"] entered-in-error
stopped --> (*)
"entered-in-error" --> (*)
completed --> (*)
@enduml