@startuml
title MedicationRequest.status (geplante Abgabe)

(*) --> [offen] active
active --> [nicht abgegeben] stopped
active --> [eingelöst\n(durch\nFachanwendung) ] completed  
active --> [storniert] "entered-in-error"
active --> [Datum abgelaufen\n(durch\nFachanwendung)] cancelled
stopped --> (*)
"entered-in-error" --> (*)
completed --> (*)
cancelled --> (*)
@enduml