@startuml

title Durchgeführte Abgaben lesen\nVariante B: Zugriff mittels e-Rezept

'skinparam actorStyle awesome

skinparam borderColor #000000
skinparam backgroundColor #f5f5f5
skinparam shadowing false
skinparam roundCorner 10
skinparam defaultFontName "Arial"
'skinparam defaultFontSize 14
skinparam defaultFontColor #000000
skinparam HyperlinkColor #0000EE
skinparam HyperlinkUnderline false
skinparam BoxPadding 20
skinparam BoxBorderColor #555555

skinparam note {
  BackgroundColor #e0e5f0-#d1d9e6
  BorderColor #8b95a5
  BorderThickness 1
  RoundCorner 0
  Padding 6
  FontColor #111827
  Shadowing false
}

skinparam sequence {
  ParticipantBorderColor #555555
  ParticipantFontColor #000000
  ParticipantFontSize 14
  ParticipantPadding 20
  ArrowColor #111827
  ArrowThickness 1
  ArrowFontColor #000000
  ArrowFontSize 13
  GroupBorderColor #111827
  GroupBackgroundColor #eef2ff
  GroupBorderThickness 2
}

!define COLOR_GDA_1    #15608280
!define COLOR_GDA_2    #96607D80
!define COLOR_PATIENT  #196B2480
!define COLOR_APO      #0F9ED590
!define COLOR_EMED_FA  #e97232bd
!define COLOR_E_REZEPT #cd3732a9

!define COLOR_OK       #0F9ED525
!define COLOR_ERROR    #E9713235

'actor GDA_1 as "GDA 1" COLOR_GDA_1
actor GDA_Apo as "Apotheke" COLOR_APO
participant eMed_FA as "e-Med FA" COLOR_EMED_FA
'participant e_Rezept as "e-Rezept" COLOR_E_REZEPT

autonumber

== Durchgeführte Abgaben abrufen  ==
'== e-Rezept + Geplante Abgaben abrufen ==

' par e-Rezept abrufen
'   GDA_Apo -> e_Rezept: e-Rezept mittels e-Rezept-ID (QR-Code) abrufen
'   activate GDA_Apo COLOR_APO
'   activate e_Rezept COLOR_E_REZEPT
'   e_Rezept --> GDA_Apo: e-Rezept 
'   deactivate e_Rezept

' else 

note over GDA_Apo
Annahme: Durchgeführte Abgabe 
speichert e-Med Groupidentifier. 
end note

GDA_Apo -> eMed_FA: GET MedicationDispense mit e-Med Groupidentifier (QR-Code)
activate GDA_Apo COLOR_APO
activate eMed_FA COLOR_EMED_FA

alt COLOR_OK e-Med GroupIdentifier gültig
  eMed_FA --> GDA_Apo: Durchgeführte Abgaben mit e-Med\nGroupidentifier
  
else COLOR_ERROR nicht gültig
  eMed_FA --> GDA_Apo: Fehler
  deactivate GDA_Apo
  deactivate eMed_FA
end

note over GDA_Apo
GDA erhält ausschließlich die Durchgeführten Abgaben, 
die den im QR-Code des e-Rezepts enthaltenen 
e-Med GroupIdentifier enthalten.
end note

@enduml