@startuml

title Geplante Abgabe für bestehende Medikationsplaneinträge erstellen\nVariante A: Vorab-Ermittlung des GroupIdentifiers (Normalfall)

skinparam borderColor #000000
skinparam backgroundColor #f5f5f5
skinparam shadowing false
skinparam roundCorner 10
skinparam defaultFontName "Arial"
skinparam defaultFontSize 14
skinparam defaultFontColor #000000
skinparam HyperlinkColor #0000EE
skinparam HyperlinkUnderline false
skinparam BoxPadding 20
skinparam BoxBorderColor #555555

skinparam note {
  BackgroundColor #e0e5f0-#d1d9e6
  BorderColor #8b95a5
  BorderThickness 1
  RoundCorner 0
  Padding 6
  FontColor #111827
  Shadowing false
}

skinparam sequence {
  ParticipantBorderColor #555555
  ParticipantBackgroundColor #ffffff
  ParticipantFontColor #000000
  ParticipantFontSize 14
  ParticipantPadding 20
  ArrowColor #111827
  ArrowThickness 1
  ArrowFontColor #000000
  ArrowFontSize 13
  GroupBorderColor #111827
  GroupBackgroundColor #eef2ff
  GroupBorderThickness 2
}

!define COLOR_GDA_1    #0078D460
!define COLOR_GDA_2    #8764B860
!define COLOR_PATIENT  #00950560
!define COLOR_APO      #00B7C360
!define COLOR_EMED_FA  #f5a40360
!define COLOR_E_REZEPT #E7485660

!define COLOR_OK       #50E6FF25
!define COLOR_ERROR    #FF8C0035

actor GDA_1 as "GDA 1" COLOR_GDA_1
participant eMed_FA as "e-Med FA" COLOR_EMED_FA
participant e_Rezept as "e-Rezept" COLOR_E_REZEPT

autonumber

== Medikationsplan abrufen ==

activate GDA_1 COLOR_GDA_1
ref over GDA_1, eMed_FA : [[interactions.html#sequenzdiagramm-plan-read Plan-Read]]


note over GDA_1
GDA erhält Medikationsplan 
(Auslieferungs-Collection-Bundle)
end note

== <i>Geplante Abgaben</i> vorbereiten und schreiben ==



GDA_1 -> eMed_FA: POST $groupidentifier-create​ 

note over GDA_1
e-Med GroupIdentifier für 
"Rezeptklammer" anfordern
end note

activate eMed_FA COLOR_EMED_FA
eMed_FA -> eMed_FA: e-Med GroupIdentifier erzeugen
eMed_FA -> GDA_1: e-Med GroupIdentifier
deactivate eMed_FA

note over GDA_1
Erstellte <i>Geplante Abgaben</i> referenzieren 
zugehörige Medikationsplaneinträge und
enthalten e-Med GroupIdentifier
end note

par Erstellung e-Rezept

  GDA_1 -> e_Rezept: Trigger e-Rezept erstellen
  activate e_Rezept COLOR_E_REZEPT
  e_Rezept --> GDA_1: OK
  deactivate e_Rezept
    
else gleichzeitige Erstellung <i>Geplante Abgabe</i>

  GDA_1 -> eMed_FA: POST $prescription-write
  activate eMed_FA COLOR_EMED_FA
  note over GDA_1
  Transaction Bundle mit Geplanten
  Abgaben an Fachanwendung übermitteln
  end note
  
  eMed_FA --> GDA_1: OK  
  deactivate eMed_FA
  deactivate GDA_1
  note over eMed_FA
  <i>Geplante Abgaben</i> erstellt
  end note

end

@enduml