@startuml

title Geplante Abgabe für bestehende Medikationsplaneinträge erstellen\nVariante C: Nachträgliche Verknüpfung des e-Rezepts mit dem e-Med GroupIdentifier

'skinparam actorStyle awesome

skinparam borderColor #000000
skinparam backgroundColor #f5f5f5
skinparam shadowing false
skinparam roundCorner 10
skinparam defaultFontName "Arial"
skinparam defaultFontSize 14
skinparam defaultFontColor #000000
skinparam HyperlinkColor #0000EE
skinparam HyperlinkUnderline false
skinparam BoxPadding 20
skinparam BoxBorderColor #555555

skinparam note {
  BackgroundColor #e0e5f0-#d1d9e6
  BorderColor #8b95a5
  BorderThickness 1
  RoundCorner 0
  Padding 6
  FontColor #111827
  Shadowing false
}

skinparam sequence {
  ParticipantBorderColor #555555
  ParticipantBackgroundColor #ffffff
  ParticipantFontColor #000000
  ParticipantFontSize 14
  ParticipantPadding 20
  ArrowColor #111827
  ArrowThickness 1
  ArrowFontColor #000000
  ArrowFontSize 13
  GroupBorderColor #111827
  GroupBackgroundColor #eef2ff
  GroupBorderThickness 2
}

!define COLOR_GDA_1    #15608280
!define COLOR_GDA_2    #96607D80
!define COLOR_PATIENT  #196B2480
!define COLOR_APO      #0F9ED590
!define COLOR_EMED_FA  #e97232bd
!define COLOR_E_REZEPT #cd3732a9

!define COLOR_OK       #0F9ED525
!define COLOR_ERROR    #E9713235

actor GDA_1 as "GDA 1" COLOR_GDA_1

participant eMed_FA as "e-Med FA" COLOR_EMED_FA

participant e_Rezept as "e-Rezept" COLOR_E_REZEPT

autonumber

== Medikationsplan abrufen ==

activate GDA_1 COLOR_GDA_1
ref over GDA_1, eMed_FA : [[interactions.html#sequenzdiagramm-plan-read Plan-Read]]


note over GDA_1
GDA erhält Medikationsplan 
(Auslieferungs-Collection-Bundle)
end note

== <i>Geplante Abgaben</i> vorbereiten und schreiben ==

note over GDA_1
Erstellte <i>Geplante Abgaben</i> referenzieren 
zugehörige Medikationsplaneinträge;
groupIdentifier für "Rezeptklammer"
bleibt leer
end note

par Erstellung e-Rezept

  GDA_1 -> e_Rezept: Trigger e-Rezept erstellen
  activate e_Rezept COLOR_E_REZEPT
  note over GDA_1
  Erstellung e-Rezept auslösen,
  ohne e-Med GroupIdentifier
  end note

  alt COLOR_OK e-Rezept erstellt
    e_Rezept --> GDA_1: OK

  else COLOR_ERROR e-Rezept Fehler
    e_Rezept --> GDA_1: Fehler 
    deactivate e_Rezept
  end

else gleichzeitige Erstellung <i>Geplante Abgabe</i>
  
  GDA_1 -> eMed_FA: POST Transaction Bundle GeplAbgabe
  
  activate eMed_FA COLOR_EMED_FA
  note over GDA_1
    Transaction Bundle mit Geplanten
    Abgaben an Fachanwendung übermitteln
  end note

  alt COLOR_OK Geplante Abgaben erstellt

    eMed_FA -> eMed_FA: e-Med GroupIdentifier erzeugen\n+ geplanten Abgaben hinzufügen

    note over eMed_FA
    Geplante Abgabe 1 + 2 
    gespeichert
    end note

    eMed_FA -> GDA_1: OK (Ressourcen inkl. e-Med GroupIdentifier)

  else COLOR_ERROR Geplante Abgabe Fehler
    eMed_FA --> GDA_1: Fehler 
    deactivate eMed_FA

  end

end

GDA_1 -> e_Rezept: e-Rezept mit e-Med GroupIdentifier verknüpfen
  activate e_Rezept COLOR_E_REZEPT
  e_Rezept -> e_Rezept: e-Med GroupIdentifier\nergänzen
  note over e_Rezept
    Bestehendes e-Rezept mit
    e-Med GroupIdentifier verknüpft
  end note
  e_Rezept --> GDA_1: OK
  deactivate e_Rezept

@enduml