@startuml

title Durchgeführte Abgabe schreiben

'skinparam actorStyle awesome

skinparam borderColor #000000
skinparam backgroundColor #f5f5f5
skinparam shadowing false
skinparam roundCorner 10
skinparam defaultFontName "Arial"
'skinparam defaultFontSize 14
skinparam defaultFontColor #000000
skinparam HyperlinkColor #0000EE 
skinparam HyperlinkUnderline false
skinparam BoxPadding 20
skinparam BoxBorderColor #555555

skinparam note {
  BackgroundColor #e0e5f0-#d1d9e6
  BorderColor #8b95a5
  BorderThickness 1
  RoundCorner 0
  Padding 6
  FontColor #111827
  Shadowing false
}

skinparam sequence {
  ParticipantBorderColor #555555
  ParticipantFontColor #000000
  ParticipantFontSize 14
  ParticipantPadding 20
  ArrowColor #111827
  ArrowThickness 1
  ArrowFontColor #000000
  ArrowFontSize 13
  GroupBorderColor #111827
  GroupBackgroundColor #eef2ff
  GroupBorderThickness 2
}

!define COLOR_GDA_1    #15608280
!define COLOR_GDA_2    #96607D80
!define COLOR_PATIENT  #196B2480
!define COLOR_APO      #0F9ED590
!define COLOR_EMED_FA  #e97232bd
!define COLOR_E_REZEPT #cd3732a9

!define COLOR_OK       #0F9ED525
!define COLOR_ERROR    #E9713235

actor GDA_Apo as "Apotheke" COLOR_APO
participant eMed_FA as "e-Med FA" COLOR_EMED_FA
' participant e_Rezept as "e-Rezept" COLOR_E_REZEPT

autonumber

activate GDA_Apo COLOR_APO 

alt Zugriff mit Kontakt (z.B. e-card)
  ref over GDA_Apo, eMed_FA : [[Sub_UC_eMed_07_01.html#sub_uc_emed_07_01_a-zugriff-mittels-e-card Geplante Abgaben lesen - Zugriff mittels e-card]]
  note over GDA_Apo
  Alle offenen e-Rezepte +
  alle offenen Geplanten Abgaben + 
  Medikationsplan abrufen
  end note
else Zugriff ohne Kontakt (e-Rezept)
  ref over GDA_Apo, eMed_FA : [[Sub_UC_eMed_07_01.html#sub_uc_emed_07_01_b-zugriff-mittels-e-rezept Geplante Abgaben lesen - Zugriff mittels e-Rezept]]
  note over GDA_Apo
  Zugehörige Geplante Abgaben mit
  e-Med Groupidentifier 
  abrufen
  end note
end
  

== Durchgeführte Abgaben vorbereiten und schreiben  ==

note over GDA_Apo
Durchgeführte Abgaben erstellen  
(referenzieren zugehörige Geplante Abgaben 
und Medikationsplaneinträge)
end note

GDA_Apo -> eMed_FA: POST Transaction Bundle MedicationDispense
activate eMed_FA COLOR_EMED_FA

alt COLOR_OK Durchgeführte Abgaben erstellt

  note over eMed_FA
  <i>Durchgeführte Abgaben</i>
  gespeichert
  end note

  eMed_FA --> GDA_Apo: OK 

else COLOR_ERROR Fehler
  eMed_FA --> GDA_Apo: Fehler 
  deactivate eMed_FA

end

@enduml