@startuml
title MedicationRequest.status (Geplante Abgabe)

(*) --> [offen] active
active --> [Geplante\nAbgabe\nabgelaufen\n(automatisch)] stopped
active --> [alle\nmöglichen\nEinlösungen\ndurchgeführt\n(automatisch)] completed
active --> [Geplante\nAbgabe\nstornieren] entered-in-error
active --> [alle\nmöglichen\nEinlösungen\nLeerabgaben\n(automatisch)] cancelled
completed --> [letzte\nDurchgeführte\nAbgabe\nstorniert\n(automatisch)] active
cancelled --> [letzte\ngecancellte\nDurchgeführte\nAbgabe\nstorniert\n(automatisch)] active
stopped --> (*)
"entered-in-error" --> (*)
completed --> (*)
cancelled --> (*)
@enduml